 /*
 CREATE TABLE CLIENTE (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	NOME VARCHAR(100),
 	EMAIL VARCHAR(100),
 	SENHA VARCHAR(100),
 );
 
 CREATE TABLE PRODUTO (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	DESCRICAO  VARCHAR(100),
 	PRECO NUMERIC(20,2)
 );
 
 CREATE TABLE  PEDIDO (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
	DATA_PEDIDO TIMESTAMP,
	TOTAL NUMERIC(20,2)
 );
 
 CREATE TABLE ITEM_PEDIDO(
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
	PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
	QUANTIDADE INTEGER 
 ); 
 */
 
 INSERT INTO CLIENTE (ID, NOME, EMAIL, SENHA) VALUES (1, 'Ian', 'ian@geobras.com', '123');
 INSERT INTO CLIENTE (ID, NOME, EMAIL, SENHA) VALUES (2, 'Roger', 'roger@geobras.com', '123');
 INSERT INTO CLIENTE (ID, NOME, EMAIL, SENHA) VALUES (3, 'Jandson', 'jandson@geobras.com', '123');
 
 INSERT INTO PRODUTO (ID, DESCRICAO, PRECO) VALUES (1, 'Samsung Galaxy S20', 4999.99);
 INSERT INTO PRODUTO (ID, DESCRICAO, PRECO) VALUES (2, 'Xaomi Mi 10T', 1999.99);
 
 