 /*
 CREATE TABLE CLIENTE (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	NOME VARCHAR(100),
 	EMAIL VARCHAR(100),
 	SENHA VARCHAR(100)
 );
 
 CREATE TABLE PRODUTO (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	NOME VARCHAR(100),
 	DESCRICAO  VARCHAR(250),
 	PRECO NUMERIC(20,2)
 );
 
 CREATE TABLE  PEDIDO (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID BIGINT(20) REFERENCES CLIENTE (ID),
	DATA_PEDIDO TIMESTAMP,
	STATUS VARCHAR(20),
	TOTAL NUMERIC(20,2)
 );
 
 CREATE TABLE ITEM_PEDIDO(
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID BIGINT(20) REFERENCES CLIENTE (ID),
	PRODUTO_ID BIGINT(20) REFERENCES PRODUTO (ID),
	QUANTIDADE INTEGER 
 );  
 
 CREATE TABLE users (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	USERNAME VARCHAR(100) NOT NULL,
 	PASSWORD VARCHAR(100) NOT NULL,
 	ADMIN BOOLEAN DEFAULT FALSE
 );
 */
 
 INSERT INTO CLIENTE (ID, NOME, EMAIL, SENHA) VALUES (1, 'Ian', 'ian@geobras.com', '123');
 INSERT INTO CLIENTE (ID, NOME, EMAIL, SENHA) VALUES (2, 'Roger', 'roger@geobras.com', '123');
 INSERT INTO CLIENTE (ID, NOME, EMAIL, SENHA) VALUES (3, 'Jandson', 'jandson@geobras.com', '123');
 
 INSERT INTO PRODUTO (ID, NOME, DESCRICAO, PRECO) VALUES (1, 'Samsung Galaxy S20', 'Smartphone Samsung Galaxy S20 Rosa 128GB, 8GB RAM, Tela Infinita de 6.2, Câmera Tripla Traseira, Câmera Frontal 10MP, IP68 e Leitor de Digital', 4999.99);
 INSERT INTO PRODUTO (ID, NOME, DESCRICAO, PRECO) VALUES (2, 'Xaomi Mi 10T', 'Smartphone Xiaomi Redmi Note 10 128GB 6GB RAM Branco', 1999.99);
 
 